### ISSUE TITLE
Generate PR for WooCommerce

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#131]
And retire this repo

**Comment by jkudish** [comment]
A reminder that when we do this we'll need to adjust the behaviour of tracking opt-in and opt-out events (see #289)

**Comment by jkudish** [comment]
We'll also need to keep an eye on #337

**Comment by allendav** [comment]
No longer a task, as Connect will NOT be delivered via a PR to WooCommerce
