### ISSUE TITLE
Support localization in React components

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-connect-client#17]

**Comment by allendav** [comment]
Closing this - it's in there. https://github.com/Automattic/woocommerce-connect-client/blob/086dbc1ded62b5f648dc2dab64877f31071362ca/client/components/shipping/services/group.js#L15

**Comment by allendav** [comment]
One question for perpetuity @jeffstieler - who sets up window.i18nLocaleStrings ?  Or maybe I closed this issue too soon?  (I don't see window.i18nLocaleStrings in my dev console while looking at the settings form.)

**Comment by jeffstieler** [comment]
> who sets up window.i18nLocaleStrings ?

@allendav The PHP client would need to do so. It currently isn't.
