### ISSUE TITLE
UX Improvement: add a check all checkbox for services

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#198]
From @kellychoffman:

There's a bulk select component in calypso that we could take advantage of

I think it would look best if instead of the count, we had the column title there. Design:

![](https://cloud.githubusercontent.com/assets/5835847/14603500/00762a54-053c-11e6-872d-ac9df82516ec.png)

Originally posted here by accident: https://github.com/Automattic/woocommerce-connect-server/issues/197

**Comment by allendav** [comment]
To me, it doesn't seem likely that a merchant would want to select all the services in a given category.

**Comment by kellychoffman** [comment]
> To me, it doesn't seem likely that a merchant would want to select all the services in a given category.

Hmm. I think we are shooting blind here. Should we add it, track it, and see what happens? We can always remove it if there's no use?
