### ISSUE TITLE
UI Improvement: Consolidate titles 

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#199]
On the USPS settings screen, there's some redundancy in USPS shipping titles because of how shipping zones is set up:

<img width="724" alt="screen shot 2016-04-18 at 8 36 30 am" src="https://cloud.githubusercontent.com/assets/5835847/14610244/10f321e2-055b-11e6-92f7-91d08dd977b2.png">

Lets combine these two. I was thinking that for now, we should get rid of the top one and add a back button to the one below. (For now, because ideally this should be fixed with a nav restructure, but that is a much bigger thing for another time.)

<img width="720" alt="screen shot 2016-04-18 at 8 37 48 am" src="https://cloud.githubusercontent.com/assets/5835847/14610241/0e75eb34-055b-11e6-9ba7-b38ac85ff031.png">

Hover:

<img width="717" alt="screen shot 2016-04-18 at 8 44 17 am" src="https://cloud.githubusercontent.com/assets/5835847/14610236/0699de98-055b-11e6-8a6f-4351d9a78885.png">

**Comment by allendav** [comment]
@kellychoffman - I think surpressing the "top one" will require filtering or something in core here https://github.com/woothemes/woocommerce/blob/cf6478644760337c18a2e675a54311c4de46fb2e/includes/admin/settings/views/html-admin-page-shipping-zones-instance.php#L9

Would you mind submitting an issue there too?

**Comment by kellychoffman** [comment]
On further thought, don't think having different titles and ways to navigate is a good idea. The current UI in the shipping zones section has the title as a breadcrumb navigation:

![screen shot 2016-06-27 at 12 21 47 pm](https://cloud.githubusercontent.com/assets/5835847/16390807/c2550a6c-3c61-11e6-8c3c-4a2095705ba4.png)

I do still think it would be nice to implement the title bar, as in the original design, even if we decide against the enable toggle in favor of doing that elsewhere:

![](https://cloud.githubusercontent.com/assets/5835847/14610244/10f321e2-055b-11e6-92f7-91d08dd977b2.png)
