### ISSUE TITLE
Use object-path for state changes

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#212]
replace the `updateValue` and `updateSub*Value` calls with one method that uses an object path (see: https://www.npmjs.com/package/object-path)

**Comment by allendav** [comment]
This should make data drivenness easier to achieve, right?

**Comment by nabsul** [comment]
@jeffstieler looked into this while working on the packages redux actions. It wasn't as straight forward as we had hoped, especially around keeping the state immutable, so we decided to just leave things as is.
