### ISSUE TITLE
Saving but keeps asking to leave the page

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/woocommerce-connect-client#221]
On Chrome, after saving the settings, if I try to leave the page it keeps asking me if I want to leave it or stay there, like if I didn't save the page:

![](http://cld.wthms.co/11qwI/1xliq4lg+)

**Comment by jkudish** [comment]
Anyone still encountering this? I haven't been able to reproduce this any longer

**Comment by SiR-DanieL** [comment]
Yep, just tested!

![](http://cld.wthms.co/1eklE/2AOmP6Bt+)

**Comment by allendav** [comment]
Since we stopped using the form-protect calypso mixin, we no longer have this issue.  When we fix this issue - #221 - we will want to make sure this doesn't come back
