### ISSUE TITLE
Alert the customer if their USPS account number isn't valid

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/woocommerce-connect-client#224]
Would it be possible to test if the customer's account number is valid when they add in their own? And if it isn't valid, have an alert show above the USPS settings?

It could be very helpful to do this in the settings on save before they start experiencing issues at checkout.

**Comment by allendav** [comment]
Closing this issue in light of https://github.com/Automattic/woocommerce-connect-client/issues/351
