### ISSUE TITLE
Handeling different currencies

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/woocommerce-connect-client#225]
The current USPS plugin shows this if the currency is not set to US dollars: http://cld.wthms.co/1kwt3/5KqJZj1U

If the WooCommerce store has a different currency set, then connect currently just changes the symbol. This could lead to some unexpected results for stores in Canada for example that have a shipping zone with USPS for US shipping.

Euro: http://cld.wthms.co/1fSMh/90bVG31H
US Dollar: http://cld.wthms.co/MQl6/3QXxW3a6
Canadian: http://cld.wthms.co/16OJG/cSamwJGB

**Comment by allendav** [comment]
New plan: we only show USPS shipping as an option if the store currency is USD. And that we only show Canada Post shipping as an option if the store currency is CAD.

**Comment by allendav** [comment]
This needs to be fixed on the server. Closing this issue.
