### ISSUE TITLE
International rates

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/woocommerce-connect-client#226]
![](http://cld.wthms.co/15GIh/1Vw0MKuo+)
![](http://cld.wthms.co/1eAgd/5ZYvWB1J+)

I have these rates enabled for the zone "Rest of the World" but on the checkout, when trying to ship from San Francisco to Italy, I get this:

![](http://cld.wthms.co/167P1/4xyjdFH0+)

I'm trying to ship here:

![](http://cld.wthms.co/1bcgy/3e9WOD7Q+)

From our Hawthorne address

Am I missing something or is there a bug?

**Comment by allendav** [comment]
Trying this again with the tagged zip - we'll get to the bottom of it

**Comment by allendav** [comment]
I just re-tested with the exact same setup as above and it is working on my test site with origin 94107

What is the exact weight and dimensions of each shippable item in your cart?

Could you try again and if it fails again reply with the relevant portion of the client logs ( wp-admin > WooCommerce > System Status > Logs > wc-connect* )

**Comment by jeffstieler** [comment]
This is also working for me.

<img width="744" alt="screen shot 2016-04-29 at 10 29 22 am" src="https://cloud.githubusercontent.com/assets/63922/14922543/659a0b96-0df5-11e6-833e-efa4992a59e0.png">

I'm using an item with dimensions: 6 x 6 x 6 in, 10g weight.

**Comment by SiR-DanieL** [comment]
Sorry, I used a new product and forgot to add weight dimensions :D

I'll check again ASAP

**Comment by SiR-DanieL** [comment]
I can confirm as well, this is fixed!

**Comment by allendav** [comment]
yay!
