### ISSUE TITLE
Deactivating legacy shipping rates

### ISSUE THREAD

**Issue by MarinaWoo** [Automattic/woocommerce-connect-client#229]
I had legacy flat rate shipping set up from my previous settings, which I did see in the shippings tab after setting up USPS - but didn't initially uncheck so USPS didn't kick in. If this might affect people switching to connect, maybe need to make more explicit that these need to be unchecked in settings.

**Comment by jeffstieler** [comment]
@MarinaWoo what PHP version is your test site running on? You can find this in the dashboard by going to WooCommerce > System Status, in the "Server Environment" box.

If your PHP version is `5.4` or higher, you're likely running into an `E_STRICT` warning related to the USPS shipping `calculate_shipping()` method. In logs, it would look like this: `Warning: Declaration of WC_Shipping_USPS::calculate_shipping($package) should be compatible with WC_Shipping_Method::calculate_shipping($package = Array) in /wp-content/plugins/woocommerce-shipping-usps/includes/class-wc-shipping-usps.php on line 0`.

As a test, I set up USPS (legacy) on WC 2.5.5, then upgraded to WC 2.6-beta-1. After this, I could no longer get rates from USPS, even before setting up WCC.

**Comment by MarinaWoo** [comment]
@jeffstieler I'm on 5.6.17, so yep sounds like that's what it is.

**Comment by Avidexp** [comment]
Did anyone come up with a solution for this yet? Been stuck on this for a solid couple hours. Know this is an old thread, just figured it wouldn't hurt to ask.

**Comment by jeffstieler** [comment]
Sorry for the late response @Avidexp - if you're still experiencing problems, can you open a new issue? Thanks!
