### ISSUE TITLE
Change usps method id to wc_connect_usps

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#235]
I noticed that currently our shipping zone `method_id` for USPS is just `usps`. Should this be something more specific like `wc_connect_usps` so that we don't conflict with other USPS integrations (once some exist for shipping zones)

cc @allendav

**Comment by allendav** [comment]
Ick. I think so. The woothemes usps extension uses id usps as well.  And looking at class-wc-shipping.php suggests nothing good will come of this :)

This is likely a breaking change for alpha clients. I think we will want to do this for Beta and beyond, but we're going to have to wait until the end of alpha, right before beta, to do it.

Ref: https://github.com/woothemes/woocommerce/blob/fa30a38c58373d9c3706cc0b7ae22032de3a2985/includes/class-wc-shipping.php#L279

also Ref: https://github.com/Automattic/woocommerce-connect-client/blob/086dbc1ded62b5f648dc2dab64877f31071362ca/woocommerce-connect-client.php#L309

**Comment by jkudish** [comment]
>  but we're going to have to wait until the end of alpha, right before beta, to do it.

Are we going to release more alphas before we release a beta? If not, then we can do this now.

**Comment by allendav** [comment]
This change actually needs to happen on the server. Closing this issue.
