### ISSUE TITLE
Add a Debug checkbox to System > Tools for logging

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#26]
At the Kelowna meetup, we decided to add a single debug checkbox to System > Tools for WooCommerce connect and its services.

**Comment by kellychoffman** [comment]
Closing this in favor of adding the 'Debug logging' toggle on the self help page: https://github.com/Automattic/woocommerce-connect-client/issues/153#issuecomment-213117660

Please reopen if you strongly feel otherwise.
