### ISSUE TITLE
Update service settings when woocommerce settings get changed

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#261]
The scenario we're thinking about specifically is if the user changes their weight or dimension units. The client will need to re-fetch the service settings (for example, the preset box sizes) so that the server returns new values with the correct units.

**Comment by jeffstieler** [comment]
> if the user changes their weight or dimension units

Do we have any handling to convert packages the user has already set up?

**Comment by nabsul** [comment]
We should probably re-fetch the presets with the new dimension unit, but not touch any already created boxes. This would keep things consistent with the way product dimensions work; if you change the units in the shop settings, the values in the product remain as they are.
