### ISSUE TITLE
Add Optional Fall Back Rate Field to USPS and Canada Post Settings

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#265]
While comparing the existing wooThemes USPS extension and the WCC USPS method, one of things that came up was that the old extension supports an optional fall back rate – one that is returned to the customer during checkout in the event that no rates are returned by USPS for whatever reason.

I’m starting to think we should have that too in our method – here’s my rationale – if for whatever reason we don’t return a rate (and we’ve seen lately how easy it is to get into that situation, although hopefully we’ve now closed some of those holes) and the merchant only has USPS shipping for the customer’s zone, that customer will simply NOT be able to complete checkout. Period.

As a merchant, this would give me much angst and reflect badly on the WCC USPS method, even if it later turns out it was due to something I did wrong (e.g. selecting a bad set of USPS services)

At least seeing the fall back rate 1) will let a customer proceed with checkout and 2) reassure me that the extension is probably working and that I need to fix a setting.

As with any other USPS service, the Edit Order page should reflect that the Fall Back Rate was the “selected” service

I realize it adds more visual clutter to the settings UI, but I think the upside greatly outweighs that downside.

cc @kellychoffman

**Comment by allendav** [comment]
> I'm just wondering though, isn't there a feature in WooCommerce itself that says "If no shipping rates are returned, do this...". I feel like I've seen this somewhere, but I might be imagining it...

There is - but it is in the USPS extension by WooThemes

**Comment by allendav** [comment]
@jkudish: for USPS, we can trigger a fall back rate quickly by having only First Class mail selected as a service and having more than 13 oz as an item weight. Do you know of a quick way to trigger something similar for Canada Post?

**Comment by jkudish** [comment]
I am sorry I don't. I am not an avid mailer like you are @allendav :wink:

**Comment by allendav** [comment]
LOL

**Comment by allendav** [comment]
No work remains on the client for this once #410 is committed. The next step will be to add this to USPS's schema like we did for Canada Post.
