### ISSUE TITLE
Review our eslint rules

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#271]
There's some improvements to do I think

**Comment by jkudish** [comment]
Agreed, though I think there's a few places where we have to deviate for React standards on the client

**Comment by jkudish** [comment]
Re-assigning to Nabeel as the second most attentive to coding standards person after me (or more than me?) :stuck_out_tongue:

**Comment by nabsul** [comment]
Done. Only some minor changes needed on the client's eslint file. PR is in review.
