### ISSUE TITLE
USPS account: Update to use our account instead of a fake placeholder

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#283]
Right now, we ask for a USPS account or to just use the one provided:

<img width="544" alt="screen shot 2016-05-03 at 1 26 01 pm" src="https://cloud.githubusercontent.com/assets/5835847/14996224/26a7d94c-1136-11e6-9bfb-e06021cb3363.png">

I think we should prefill this with our account info instead of using a placeholder text. That way it appears that its already "done" to someone who doesn't want to make an account. For those that do (or already have one) they know to just add theirs.

The existing extension uses 150WOOTH2143. Assuming that is still the account, I think we should use that as the added value in that input.

**Comment by jkudish** [comment]
I agree. I also think we should move this field somewhere less prominent. What do you think @kellychoffman ?

**Comment by nabsul** [comment]
I think we should either decide to remove it altogether or start supporting Commercial and CommercialPlus rates.

**Comment by nabsul** [comment]
There is one issue by the way with moving away from the placeholder: If the user overrides the field with their own value and then decides to go back to our key, where will they get that value from? I guess we'd have to mention the default key in the description below the field?

**Comment by kellychoffman** [comment]
Originally it was in a less prominent location, but after talking to @shaunkuschel I moved it up a level because of how often its used. 

> I guess we'd have to mention the default key in the description below the field?

Yes, I would amend the description to say: 
_Use the provided `150WOOTH2143` account or [sign up for your own](#)._

**Comment by jkudish** [comment]
I can snag this one

**Comment by allendav** [comment]
Closing this issue in light of https://github.com/Automattic/woocommerce-connect-client/issues/351
