### ISSUE TITLE
Automatically detect new API versions and auto upgrade

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#301]
This is not a duplicate of #299 - this describes a client automatically detecting new versions on the server and upgrading itself.  This will help us avoid having to roll the client to support new versions on the server.

Here's how this might work:
* every server response will include the id of the latest version the server supports
* the client will see that that is higher than what the client is currently handling
* the client will attempt to validate all active instance settings against the newer version endpoint
* if those all succeed, the client will request the latest version schemas and start making requests with the new version
* if one or more fails (e.g. a new required field) then we will continue to use the old version
* we’ll then tell the merchant that a new version of the api is available, but that they’ll need to fill in some required fields once they accept it
* they’ll hit accept, and the help page will show them all the services that need settings fixed
* if they panic, ideally they should ideally be able to roll back to the previous version

**Comment by allendav** [comment]
Not sure if we need this just yet - if we introduce new versions of the API no more frequently than new versions of WooCommerce, then we won't need this data-driven upgrade concept

**Comment by nabsul** [comment]
I agree that we should consider whether or not this is really an essential requirement for our service.

**Comment by allendav** [comment]
Closing this until needed
