### ISSUE TITLE
We should validate fields in the modal before leaving the modal

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#306]
![we-really-should-validate-while-in-the-modal](https://cloud.githubusercontent.com/assets/1595739/15086650/124e60e8-1397-11e6-81cb-90d9f353a715.gif)

cc @kellychoffman - do you concur?

**Comment by jkudish** [comment]
@jeffstieler and I just discussed this. We agreed that:

* We'll have client side validation for the package to be able to show inline errors
* We'll also have server side validation for packages. Most users won't encounter this (since they'll hit client side validation first), but we'll need to be safe. Any returned errors from the server can highlight the package in question with a message to go and fix that package. We can then show the specific error in the modal. We'll need some design for this @kellychoffman

**Comment by kellychoffman** [comment]
> do you concur?

I do indeed.

**Comment by kellychoffman** [comment]
> We'll also have server side validation for packages. Most users won't encounter this (since they'll hit client side validation first), but we'll need to be safe. Any returned errors from the server can highlight the package in question with a message to go and fix that package.

Can you better explain this? Maybe with an example? I'm not sure I fully understand.

**Comment by jkudish** [comment]
> Can you better explain this? Maybe with an example? I'm not sure I fully understand.

Yeah sorry, re-reading myself I see that it's not 100% clear. 

In other words: when you add/edit a package we'll have instant client-side validation so you can immediately see any errors. We can disable the "add package"/"save changes" button until validation passes. However, we'll also need/have server-side validation which occurs after one clicks the main "Save changes" button of the form. Most users will have failed client validation so won't trigger an error with packages at this stage, but if they do, we'll need something to indicate which of the already saved boxes has an issue they need to address. 

Does that make sense?

**Comment by kellychoffman** [comment]
Here's what I'm thinking:

We disable the 'Add packages' button until all the required fields are filled out. This way no packages will get added unless they are valid. In theory, anyway. When I was talking to @jeffstieler earlier, he mentioned it might be a good idea to plan for this anyways. 

**Add packages modal** 

On open: 
(disabled primary button)

<img width="511" alt="screen shot 2016-05-16 at 7 46 39 pm" src="https://cloud.githubusercontent.com/assets/5835847/15308879/f34c5974-1b9e-11e6-86ec-8745e1f02def.png">

With error: 
(contextual error message, primary button still disabled)

<img width="514" alt="screen shot 2016-05-16 at 7 55 22 pm" src="https://cloud.githubusercontent.com/assets/5835847/15309024/2f71172c-1ba0-11e6-95a9-390755220b2c.png">

All good:
(primary button actived)
<img width="519" alt="screen shot 2016-05-16 at 4 08 34 pm" src="https://cloud.githubusercontent.com/assets/5835847/15308837/8525f50e-1b9e-11e6-9ea0-9904b28f5bdc.png">

**Package list** 

With error:
(Click to open modal and fix)
<img width="660" alt="screen shot 2016-05-16 at 8 13 40 pm" src="https://cloud.githubusercontent.com/assets/5835847/15309286/c005445a-1ba2-11e6-926f-6bf2290d558d.png">

**Comment by kellychoffman** [comment]
Error state for packages: 

<img width="489" alt="screen shot 2016-05-17 at 11 15 15 am" src="https://cloud.githubusercontent.com/assets/5835847/15338614/e8aa120a-1c3d-11e6-8f3b-ac8c4a78292a.png">
