### ISSUE TITLE
Flat Rate Box Dimensions should probably not be editable

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#307]
otherwise the merchant could make the box dimensions wrong (e.g. bigger) and then box packing could put a too-large item in the box and then the merchant would potentially have to pony up more $ at the post office to ship the item

![should-flat-rate-boxes-be-editable](https://cloud.githubusercontent.com/assets/1595739/15086833/84b91424-1398-11e6-89db-5fbd90232502.gif)

cc @kellychoffman for thoughts

**Comment by kellychoffman** [comment]
I agree. These shouldn't be editable.
