### ISSUE TITLE
Tabbing around the services foldable cards is a bit weird

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#309]
You can tab from field to field in the Setup part of USPS settings, but if you press tab on the origin field, you have no visual indicator that the first service group chevron is now selected.  **We should probably show the chevron outline then or highlight it blue or something.**  Thankfully, spacebar will open and close the group as it should.

If you tab again, focus shifts to the next group's chevron as it should, but again, you can't tell unless you press space to toggle the group open and closed.

If a group is open, tabbing off the chevron does focus the first service's checkbox as expected.

cc @kellychoffman - what should we do with a focused chevron? outline? color change?

**Comment by allendav** [comment]
see also https://github.com/Automattic/woocommerce-connect-client/issues/310#issuecomment-217579672

**Comment by kellychoffman** [comment]
> what should we do with a focused chevron? outline? color change?

Created a PR to add a color change: https://github.com/Automattic/woocommerce-connect-client/pull/314
