### ISSUE TITLE
Tabbing around packages is a bit weird too

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#310]
If you focus on "When cheaper" and hit tab, I'd expect the first box's edit link to highlight/outline such that spacebar would open editing for it. Instead, apparently the delete X is focused instead, and hitting spacebar causes an unexpected delete.

This might be due to the lack of href that @jkudish pointed out that also causes #308 

If we fix that, maybe this will be fixed too, but we also should highlight/outline the delete X when it is focused.

cc @kellychoffman 

![unexpected-delete-on-space](https://cloud.githubusercontent.com/assets/1595739/15087491/eca20820-139d-11e6-971a-979de977dc5a.gif)

**Comment by allendav** [comment]
fwiw, we do get a highlight and outline for focussed links in the modal that we might want to emulate here?

<img width="472" alt="screen shot 2016-05-06 at 3 32 11 pm" src="https://cloud.githubusercontent.com/assets/1595739/15087666/cb518bf8-139f-11e6-9f71-804e16462d18.png">

**Comment by kellychoffman** [comment]
> If we fix that, maybe this will be fixed too, but we also should highlight/outline the delete X when it is focused.

This is broken in Calypso. I think changing it there first would be the best way to go.

**Comment by kellychoffman** [comment]
I created a PR to change the borderless button focus style in Calypso: https://github.com/Automattic/wp-calypso/pull/5274

**Comment by kellychoffman** [comment]
Fixing this in #323 instead.

**Comment by nabsul** [comment]
Looks like this got fixed a while back.
