### ISSUE TITLE
Packages: Bug when adding a second of the same predefined package

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#321]
Right now, we allow adding the same flat rate package multiple times. We probably shouldn't allow this. Here's whats happening:

![dupes](https://cloud.githubusercontent.com/assets/5835847/15154843/ec298d1c-169c-11e6-9bc6-01f751ec2060.gif)

- The name still shows up
- The package name isn't populated 
- The dimensions don't display

cc: @nabsul

**Comment by nabsul** [comment]
Great point!

**Comment by nabsul** [comment]
This appears to have been fixed along the way.
