### ISSUE TITLE
Global save validation: Update UI

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#322]
When 'Save changes' is pressed, the success notice is within the button bar at the bottom of the page:

<img width="707" alt="screen shot 2016-05-10 at 10 58 46 am" src="https://cloud.githubusercontent.com/assets/5835847/15155109/3f7e424a-169e-11e6-9185-c8b87eeee26f.png">

We should take advantage of [calypso's global notice](https://wpcalypso.wordpress.com/devdocs/design)  component instead. Its meant for a "page" wide notice, is fixed so it will always show, and can be configured to disappear after a set amount of time.  An example:

![global notice](https://cloud.githubusercontent.com/assets/5835847/15155223/be7b2356-169e-11e6-8611-18408f2e1156.gif)

**Comment by jkudish** [comment]
Looked into this a bit. It's a bit trickier then you'd think because the Global Notices component in Calypso relies on part of the Calypso redux state stree (specifically a list of `notices`), which we'll need to hack around. To be continued...
