### ISSUE TITLE
Packages: Make dimension spacing consistent

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#324]
Right now, when you add your package dimensions, it takes whatever spacing you add. Lets make it consistent like the original design: 

<img width="559" alt="screen shot 2016-05-10 at 12 20 33 pm" src="https://cloud.githubusercontent.com/assets/5835847/15157614/a113e54a-16a9-11e6-8d24-0cc732dff176.png">

This is how its currently behaving:

![dimension spacing](https://cloud.githubusercontent.com/assets/5835847/15157583/8f8c77c4-16a9-11e6-8316-8da426b8d347.gif)

cc: @nabsul

**Comment by nabsul** [comment]
Validation that the format is correct before adding the package will come next week hopefully. However, it would be really cool if we could automatically append "x " when the user types the first space after a number, or something like that.

However, I do wonder if there's a good data-driven way to do this. It might need some very custom logic. 

@jeffstieler @jkudish @allendav: Thoughts?

**Comment by jkudish** [comment]
> Validation that the format is correct before adding the package will come next week hopefully. However, it would be really cool if we could automatically append "x " when the user types the first space after a number, or something like that.

The best way to achieve this would to have 3 separate inputs but style it in a way that looks like a single input and work some javascript magic to make it behave like a single input. We have room to innovate here.

**Comment by nabsul** [comment]
> The best way to achieve this would to have 3 separate inputs but style it in a way that looks like a single input and work some javascript magic to make it behave like a single input. We have room to innovate here.

That sounds pretty cool, but I can't quite visualize it. 
@jkudish: Can you point to any examples of this?
@kellychoffman: What do you think?

**Comment by kellychoffman** [comment]
I _think_ that would be cool, I'd have to see/try an example. @jkudish: are you thinking something like how some credit card number inputs are done? In that the groupings of 4 are separate inputs, but you can keep typing and it auto-advances you to the next field as you keep typing.

**Comment by jkudish** [comment]
That's exactly what I'm thinking @kellychoffman **mind reader**

**Comment by jkudish** [comment]
I haven't found a dimensions-specific example, but [here's a set of more general examples](https://igorescobar.github.io/jQuery-Mask-Plugin). Turns out this is called "input masking"

**Comment by jeffstieler** [comment]
Here's a mixin to add masks to React components: https://github.com/borbit/react-mask-mixin

Note: I have not tested this.
