### ISSUE TITLE
Don't require formSchema to include "required" array 

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#327]
Right now, if the formSchema doesn't include the `required` array, we red screen. Let's make our processing tolerate omission of the `required` array in the formSchema.

**Comment by jkudish** [comment]
Can you give an example of how this breaks? 

PS: I think I broke it

**Comment by allendav** [comment]
This isn't happening right now on master.

In the process of wiring up the help schema, I realized that we red screen if this property is absent. For a quick hack, just remove that property before passing the schema up here https://github.com/Automattic/woocommerce-connect-client/blob/master/woocommerce-connect-client.php#L288
