### ISSUE TITLE
Bug: Shipping not calculated in cart view

### ISSUE THREAD

**Issue by dougkeeling** [Automattic/woocommerce-connect-client#330]
It appears that shipping rates are being calculated perfectly at checkout, however the "Calculate Shipping" option in the cart view accepts your selections (State, Zip) but does not return the rates/options.  

If this isn't a supported feature yet, my apologies for the wasted issue.  

Fresh install of WP 4.5.2, WooCommerce 2.6, Jetpack 3.9.6, and WooCommerce Connect.

**Comment by jeffstieler** [comment]
Hi @dougkeeling! Thanks for taking the time to test and create an issue.

We're aware of the cart page shipping calculation bug, and have already resolved it, although after we cut a .zip for Alpha testing. Good eye!

If you're interested in seeing the original issue, and the fix, please refer to the links below:
* https://github.com/Automattic/woocommerce-connect-client/issues/222
* https://github.com/Automattic/woocommerce-connect-client/pull/287

Thanks again for testing, and please don't hesitate to create more issues!
