### ISSUE TITLE
Copy over and use Calypso's Localize

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#331]
@mtias pointed out to me that Calypso now has a separate utility that might be able to be used instead of what we've done with https://github.com/Automattic/woocommerce-connect-client/blob/master/client/lib/mixins/i18n/index.js

It is here and it wrappers calypso components - https://github.com/Automattic/wp-calypso/tree/master/client/lib/mixins/i18n/localize

I have an outstanding question to @mtias about whether or not that would also satisfy the translate for child components that the wrappered component's render creates - so we'll see

cc @jkudish @jeffstieler @coderkevin

**Comment by jeffstieler** [comment]
I don't think that we can use this directly from our Calypso dependency without deciding to use *all* of Calypso's translation, including Jed.

We could copy over the `Localize` higher-order component though, and avoid using the `ReactInjection` technique.

**Comment by allendav** [comment]
> We could copy over the Localize higher-order component though, and avoid using the ReactInjection technique.

Let's do that. Changing this to bug.

**Comment by jeffstieler** [comment]
> We could copy over the Localize higher-order component though, and avoid using the ReactInjection technique.

Revisiting this - we can't just "copy over" Calypso's component as I previously thought.

While we can create our own higher-order component for localization, all we really end up changing (for now) is the injection technique.

Considering we don't get any of this "for free" - is it still worth doing?

**Comment by allendav** [comment]
Nah. it seems like, at this time, there isn’t much benefit for us. It would be more important to see what wc core is doing in this regard to make our eventual merge less painful

cc @coderkevin

**Comment by allendav** [comment]
Closing this issue. We can open a new issue to mimic core's approach when we are ready.
