### ISSUE TITLE
If Jetpack is_staging_site, add notice to health page and don't bump stats

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#336]
Jetpack has a `Jetpack::is_staging_site()` function which, if true, should prevent "syncing" of the site to WP.com. I don't think we should consider it as a full "killswitch" flag for WCC, but we may want to scale some things back (like not bumping any stats) when it returns true, and perhaps showing that on the health page (e.g. "This is a staging site, some features may not work as expected") (cc @allendav) as well.

h/t @kraftbj

**Comment by allendav** [comment]
I agree. Let's kill bumping stats and add this to the health page. Changing this question to bug.
