### ISSUE TITLE
Alert the user if schema hasn't been fetched in X days

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#339]
I know the self-help page will show this, but I can imagine a scenario where the user:

* Had connected Jetpack and set-up WooCommerce Connect succesfully
* Something happened and Jetpack got disconnect
* The setting screens continues to work because the schema is still saved
* The user doesn't know things are broken so doesn't visit the help page

We should consider a notice if the schema hasn't been updated in X days and/or if the last X requests to the server has failed. The notice can be a link to the self-help page.

**Comment by allendav** [comment]
Kinda duplicate of https://github.com/Automattic/woocommerce-connect-client/issues/18 ?

**Comment by jkudish** [comment]
Yes most definitely. I searched, but didn't find it. My bad.
