### ISSUE TITLE
Warning from the packages code

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#340]
I started getting this error:

> Warning: Failed propType: Required prop `data.inner_dimensions` was not specified in `PackagesListItem`. Check the render method of `PackagesList`.

I also see this:

![image](https://cloud.githubusercontent.com/assets/260253/15233654/3ceb2080-185f-11e6-85fe-f608015448b1.png)

![image](https://cloud.githubusercontent.com/assets/260253/15233661/489c6e48-185f-11e6-8193-1fac287631f0.png)

cc @nabsul

**Comment by nabsul** [comment]
@jkudish I believe this is not happening any more. Are you still seeing it?

**Comment by jkudish** [comment]
Yeah I don't get this anymore
