### ISSUE TITLE
Limit the number of rates returned?

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#342]
I enabled all the rate types and I got this when trying to checkout:

![image](https://cloud.githubusercontent.com/assets/260253/15235823/b6c931c6-1873-11e6-831c-470b381dffba.png)

Several problems:
* Kinda overwhelming
* Doesn't display all of them (cut-off) in Storefront
* Horrible UX for customers

Maybe we should make "informed" decisions and only display X of the returned rates?

**Comment by allendav** [comment]
I agree that the list is long, but this only happens if the merchant 1) selects that many services when setting up the instance and 2) decides to show all rates to the customer.

I think #1 is going to be rare. Rare enough to not pursue this issue, so I'm closing this as no plan to fix.
