### ISSUE TITLE
Saving a package without exterior dimensions results in horrible things

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#346]
![image](https://cloud.githubusercontent.com/assets/11143071/15365512/500ea6f8-1cd5-11e6-9b9f-fb562379e276.png)

![image](https://cloud.githubusercontent.com/assets/11143071/15365518/53e02a4a-1cd5-11e6-8c5e-ec77c0c0f527.png)

**Comment by jeffstieler** [comment]
Fixed in #354.
