### ISSUE TITLE
Delete the USPS API Key field from the settings

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#351]
Since we decided in CanadaPost not to have a username and password field for the user to enter, I'm thinking we should do the same in USPS for the sake of consistency. Right now we only support shipping rates (not labels), and standard retail rates, so there's really no point to having that field.

![image](https://cloud.githubusercontent.com/assets/11143071/15435712/c220f1c6-1e72-11e6-929e-3676f4b38319.png)

@allendav @kellychoffman

**Comment by allendav** [comment]
Great question. So, the only reason to have this field is for a user to get some kind of commercial rates by using their account, right? And if we have no means of returning those rates then we should probably remove this AND add a parked issue to add commercial rate/account support l8rs.

**Comment by kellychoffman** [comment]
If we can't return commercial rates, I see no reason keeping that field. Thats the only reason I originally had it in there to begin with so I'm fine with 🔪 it.

**Comment by allendav** [comment]
Turning this into a bug
