### ISSUE TITLE
Attempting to add two boxes results in shenanigans

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#353]
Observed on master today when working with canada post

![add-second-box-read-only](https://cloud.githubusercontent.com/assets/1595739/15437365/84eea9d4-1e7b-11e6-9dda-99f720c38314.gif)

**Comment by jeffstieler** [comment]
I can no longer reproduce this @allendav - can you?

**Comment by allendav** [comment]
Nope - appears collaterally fixed :) Closing
