### ISSUE TITLE
Notices List key prop warning

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#360]
![validator-notice-keys](https://cloud.githubusercontent.com/assets/1595739/15552783/d7e6bbb0-2270-11e6-8708-32c426256b80.gif)

**Comment by jkudish** [comment]
You need to run latest calypso (see https://github.com/Automattic/woocommerce-connect-client/pull/350#issuecomment-221061061). This warning will go away if you:  `rm -rf node_modules/wp-calypso && npm cache clean && npm install`
