### ISSUE TITLE
Packing method radio button when there are no packages defined.

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#361]
![image](https://cloud.githubusercontent.com/assets/11143071/15554715/625b0216-227a-11e6-8047-faa6af87b266.png)

When there are no packages defined, the radio buttons above the package list make no sense. We could:

1) Just hide it altogether.
2) Gray it out and set the value to "pack individually"
3) Just leave it as is for simplicity.

Suggestions?

@kellychoffman @allendav @jeffstieler @jkudish @DanReyLop

**Comment by allendav** [comment]
I agree - let's hide it when no packages are defined. Shouldn't we also make the default the "original packaging" setting too?

**Comment by nabsul** [comment]
I don't think we should make "original packing" the default. The default should be to "pack multiple" (if there are packages defined).
