### ISSUE TITLE
Add a package modal cut off on short browsers

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#363]
Minor browser quirk:

![image](https://cloud.githubusercontent.com/assets/260253/15560128/53069a3c-229d-11e6-8999-4092d4da87f8.png)

The modal is cut off when I have the developer console, and it would be the same if the user had a short browser window for some reason. We should make sure it let's you scroll to the buttons

**Comment by allendav** [comment]
Yeah, this is annoying. Please also try/fix mobile.

**Comment by nabsul** [comment]
Does anyone know off the top of their head the css needed to fix this? Or should I research it?

@kellychoffman @allendav @jeffstieler @jkudish

**Comment by kellychoffman** [comment]
I think we should do what we're doing in Calypso when you add media:

I think the only major change we'd need to make is: absolutely positioning the modal and the bottom save container. And doing a bunch of percentage based height and width adjustments. I did it quick in the browser and it works pretty good. I can take this one over @nabsul.

![quick mock](https://cloud.githubusercontent.com/assets/5835847/15622968/d0f05c1e-242b-11e6-8768-4b4685d9abcb.gif)
