### ISSUE TITLE
Test building with node 6.2

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#367]
Why? Calypso is about to jump to 6.2: https://github.com/Automattic/wp-calypso/pull/5595

cc @gwwar

**Comment by jkudish** [comment]
Preliminary findings are that we should upgrade node-sass today to ensure future compatibility. Outside of that everything seems fine. I'll submit a PR for that on Monday.

**Comment by gwwar** [comment]
@jkudish The upgrade is currently blocked by Desktop requirements, so no rush on this one.

**Comment by jkudish** [comment]
Using the latest versions of many of our dependencies (via #372) and having run `npm rebuild node-sass` (which took a bit of fiddling to cooperate on Windows bu that's beside the point), everything seems functional with node 6.2.0. Tests pass, and the build works just fine.

In theory we could upgrade once #372 is merged in, without waiting on Calypso to "officially" upgrade. Still probably safest to wait until Calypso upgrades.

**Comment by jkudish** [comment]
Re-assigning to you @allendav so you can decide next steps.

**Comment by gwwar** [comment]
@allendav do you mind testing with node 6.1.0? The Calypso node upgrade PR is now unblocked 😄

**Comment by allendav** [comment]
Tested `npm run dist` and `npm start` approaches without issue with node 6.1.0
