### ISSUE TITLE
Packages: Error on dimensions when no space is present

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#377]
Originally brought up here: https://github.com/Automattic/woocommerce-connect-client/pull/364#issuecomment-222883503

 I get an error on the dimensions if I don't add a space in between the `x`s.

![](https://cloud.githubusercontent.com/assets/5835847/15697363/95145210-2776-11e6-9511-6d4cdff9c703.gif)

**Comment by allendav** [comment]
This is so odd. I swore I already wrote an issue for this but I cannot find it

**Comment by nabsul** [comment]
@allendav I think you did too. If I find it I'll attach it to the PR.

**Comment by nabsul** [comment]
#324

**Comment by kellychoffman** [comment]
Haha, duped my own issue.
