### ISSUE TITLE
Number fields should validate when empty

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-connect-client#397]
As a follow-up to #396, the client validation should allow number fields to be empty, rather than forcing them to be zero.

**Comment by allendav** [comment]
@DanReyLop - with https://github.com/Automattic/woocommerce-connect-client/pull/410 we can close this one, right?

**Comment by DanReyLop** [comment]
It would be better that the field could be empty instead of forcing a `0` there, but that's not easy to do until we decouple the form UI values from the Redux state (as we discussed).

I'll leave this open as a reminder, but descope it from Alpha 2.

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-connect-client/issues/430.
