### ISSUE TITLE
[Labels] Consider generating the Label printing form schema & layout in the WCC server

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-connect-client#436]
Right now, the Label printing flow schema and layout are generated in the merchant host (see class `WC_Connect_Shipping_Label`).

When the form structure is stabilized, we should consider moving it to the WCC server so we can change it without modifying the client.

**Comment by allendav** [comment]
Moving this to sprint 5 since we are discussing NOT data driving labels at that time

**Comment by allendav** [comment]
Closing. No plan to do this now.
