### ISSUE TITLE
[Labels] Packaging step

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-connect-client#445]
Mock-up: TBD

In this step, the UI must display the user's "Shopping Cart". For each box the merchant will have to send, we must display at least:
* Dimensions of the box (so he knows what box to pick)
* List of products that should go into that box
* Total weight of the box and its contents
* The weight should be editable

There are 2 use cases:
* The user selected a shipping method powered by WCC, so the order metadata has all the packaging information. In that case, that information should be used.
* The user selected free shipping. In that case, we don't have the packaging information in the order metadata. In that case, **for the first iteration**, all purchased items will be "packaged" individually, in a box with the same size and weight as the item itself.

**Comment by allendav** [comment]
I'm assigning this issue to Sprint 3. If you'd like, please open a separate issue for the free shipping flow you mention in the description above for Sprint 4.
