### ISSUE TITLE
Shipping label modal scroll isn't clear

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#457]
I just want to put this as a reminder. On my mac in chrome at least, it's not very clear that the modal is scrollable.

![image](https://cloud.githubusercontent.com/assets/11143071/16799306/689ce3a0-48f0-11e6-8ed4-6c2f52a2847a.png)

@kellychoffman

**Comment by allendav** [comment]
Closing this in light of #480
