### ISSUE TITLE
[Labels] Style all the things

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#461]
The tab bar and the content for each tab need some styling :)

@DanReyLop please get this roughly styled by the end of Sprint 3 and then @kellychoffman can give it a UX review and deep styling while we're on support week

**Comment by kellychoffman** [comment]
Related comment: https://github.com/Automattic/woocommerce-connect-client/pull/458#issuecomment-235147298

TL;DR: If you could just add some classes to the surrounding div, ul, and li's I can take it from there. Or show me how to do it :)

**Comment by DanReyLop** [comment]
I'm trying to style it myself, I'll push what we have to this issue in a day or 2, and then all the classes will be in place, you will only need to clean-up my mess :D

**Comment by kellychoffman** [comment]
Thanks @DanReyLop :) Let me know I can help.

**Comment by kellychoffman** [comment]
Updating this issue definition to be: 

At the end of Sprint 5, shipping labels will have a production-ready level of design.

**Comment by allendav** [comment]
@kellychoffman - let's open new issues for style probs and close this, ok?
