### ISSUE TITLE
Canada Post rate requests failing intermittently

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#464]
I noticed that frequently, even when a address is filled in in checkout correctly, we're displaying no Canada Post rates.  A refresh of the page yields rates.  Let's get to the bottom of this.

The setup was as follows:
- WooCommerce 2.6.3
- Canada based store
- CAD currency
- lbs and inches units
- US Shipping Zone, Canadian Shipping Zone and Rest of the World Shipping Zone
- Canada Post Powered by WooCommerce Connect in US Shipping Zone with USA services all selected and origin post code V1T 2B8
- Canada Post Powered by WooCommerce Connect in Canadian Shipping Zone with domestic services all selected and origin post code V1T 2B8
- Rest of the World Shipping Zone has no methods
- Single item in cart - a half pound item measuring 3" x 3" x 2"

**Comment by robobot3000** [comment]
It doesn't look like this is reproducible anymore.
