### ISSUE TITLE
Labels: Retain origin address

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#466]
Original comment: https://github.com/Automattic/woocommerce-connect-client/pull/458#issuecomment-235107449

> It seems that once you've entered an origin address and hit next, that even if the label flow is not completed, that origin address should be retained on the merchant's host. 

Related: we should also skip this step if its already known (and prefilled)

**Comment by DanReyLop** [comment]
This is already implemented in `master`

**Comment by allendav** [comment]
It seemed to be broken in `add/label-address-suggestion` yesterday?

**Comment by DanReyLop** [comment]
`add/label-address-suggestion` was created from an older version of `master`, it didn't have the feature yet and I didn't bother to rebase. Probably I should have :)
