### ISSUE TITLE
Use autoprefixer to support non-standard CSS vendor prefixes

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-connect-client#468]
We are currently not using `autoprefixer`, so CSS rules like `display: flex` will be ignored by older browsers that only understand vendor-specific syntax (`-webkit`, `-moz`, etc).

We should use `autoprefixer` and while we are at it, remove vendor-specific CSS rules from our code, since they will be auto-generated.

**Comment by allendav** [comment]
@DanReyLop  - which older browser are you trying to fix flex for? IE8?

**Comment by DanReyLop** [comment]
@allendav This is not about Flex in particular. We are using plenty of CSS rules without worrying about browser prefixes, kind-of assuming that something in the build script was taking care of that, but it wasn't :D

The `autoprefixer` too by default generates prefixes if there are needed for any of the lates 2 versions of any major browser, or any browser version that has more than 1% of global market share. So, not IE8, but IE11 for sure.
