### ISSUE TITLE
Share custom packages across shipping method instances AND labels

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#476]
Right now custom packages are defined only within the context of a shipping method instance, i.e.:

![screen shot 2016-08-04 at 10 40 42 am](https://cloud.githubusercontent.com/assets/1595739/17412117/eebbc014-5a2f-11e6-88e8-2d57fd7cafb2.png)

If you add another instance, you have to add packages again.

#449 will also add another consumer of custom packages - the labels ui

We should come up with a means of having a single source of custom package truth that can be used by instances, the labels ui and beyond, so that merchants are not potentially having to enter custom package information repeatedly.

This may be mostly behind-the-scenes work - with the exception that the labels ui would need to add in something like what shipping method instances already have.

**Comment by kellychoffman** [comment]
> We should come up with a means of having a single source of custom package truth that can be used by instances, the labels ui and beyond, so that merchants are not potentially having to enter custom package information repeatedly.

Yes! I was struggling with whole idea while designing the Packages step in the shipping label creation flow. Sharing custom packages across methods and labels makes complete sense to me. 

What if you are creating a label for the first time and haven't saved a custom package yet, but while you are going through the flow, you realize how many times you'll probably be doing this with the same few packages. I'm just not sure how much it makes sense to do this from a users perspective. Do they want this in the label creation flow?

For the packages step, I think we have three options:

- Let users add a package, with the ability to save and reuse later (we'd be creating two places to do the same thing)
- Add a link off to centralized place to do so (flow could get messy)
- Only allow you to enter the weight of the package (leave the package creation out of the label ui)

**Comment by allendav** [comment]
Adding @kellychoffman for design
