### ISSUE TITLE
Shipping labels not loading: Update message

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#478]
Right now, when there's an error and the labels won't display, we show this message:

<img width="302" alt="screen shot 2016-08-04 at 12 55 02 pm" src="https://cloud.githubusercontent.com/assets/5835847/17417539/1c68d60c-5a51-11e6-9586-f33c6816829b.png">

It works for the settings page, but should be updated to make more sense in the context of a metabox in the Orders page. 

I think it could say something like:

> Shipping labels not loading? Visit the debug page for troubleshooting steps.

**Comment by DanReyLop** [comment]
Also we need to remember to change the rest of the places where we use the "WooCommerce Connect" name.

**Comment by robobot3000** [comment]
Fixed in #489 - the new messages are: "Shipping labels not loading? Visit the status page for troubleshooting steps." and "Settings not loading? Visit the status page for troubleshooting steps."
