### ISSUE TITLE
Replace tabbed labels UI with one-form approach

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#480]
![adding-weight-packages-added](https://cloud.githubusercontent.com/assets/5835847/17911197/96147f90-6949-11e6-8594-7486a9023ae1.png)

Full mocks: #501 

- [x] Dialog basic structure
- [x] Origin Address step
- [x] Destination Address step
- [x] Packages step
- [x] Rates step
- [x] Preview step
- [ ] Print the label & store in the order meta-data

Stretch tasks:
- [ ] Normalize Origin Address
- [ ] Normalize Destination Address
- [ ] Call the server box-packer if the order doesn't have packaging info
- [ ] Call the server shipping-rates endpoint to allow the merchant to choose the rates

**Comment by allendav** [comment]
@DanReyLop - please add a prioritized checklist of tasks to this issue - ideally split so that we can get label purchases (when a rate and packing solution is available from checkout) working this week and everything else in sprint 5 (e.g. don't bother doing address normalization now)

**Comment by DanReyLop** [comment]
@allendav I've just added a checklist. I'll have the first set (basic tasks) ready tomorrow. I'll push it ASAP so Kelly can play with the UI and Marcin can work on the refunds flow.

**Comment by allendav** [comment]
Thank you @DanReyLop ! If it is possible to connect the Buy & Print button first (and fill in the preceding step content later) please do so so we can exercise @jeffstieler 's endpoint sooner than later
