### ISSUE TITLE
Rename WooCommerce Connect

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#486]
Replace any user facing `WooCommerce Connect` string with the final name provided by marketing.

Assigned to @warrendholmes for the name, then will assign to a dev.

Note: This will also affect the name that appears in the WordPress.org repository of course.

i.e., in these places:

![screen shot 2016-08-15 at 12 19 23 pm](https://cloud.githubusercontent.com/assets/1595739/17676286/b0936fa6-62e2-11e6-95f9-b8a1738e624e.png)

![screen shot 2016-08-15 at 12 22 13 pm](https://cloud.githubusercontent.com/assets/1595739/17676354/0cfc918c-62e3-11e6-9f43-7bfff5fdfd8f.png)

![screen shot 2016-08-15 at 12 21 08 pm](https://cloud.githubusercontent.com/assets/1595739/17676311/db53bdcc-62e2-11e6-95cf-811bffa4ccf1.png)

**Comment by allendav** [comment]
Moving this to Sprint 5 / due 9/9 since name change is supposed to be available by the end of the month.

**Comment by warrendholmes** [comment]
@allendav Sorry for the delay here. Let's stick with Connect for WooCommerce.

**Comment by allendav** [comment]
Agreed! Closing this issue.
