### ISSUE TITLE
Replace tabbed labels UI with one-form approach: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#501]
Design for issue #480 of the same name. (Broke these all out into smaller issues, but keeping the full flow attached to this issue) #509 #510 #511 

# One-form design
Design reference for PR #491 

Desktop:

The modal approx 90% width, much like the Media Modal in the Calypso editor. It is split up into 2 columns, which scroll independently. The preview displays on the right sidebar and the main content of the shipping labels displays on the left within expandable cards. Upon opening, the Packages card is expanded only if there are no errors in any other cards. If a card does have an error, that one is open as to draw attention to it.

![one-form-design](https://cloud.githubusercontent.com/assets/5835847/17945755/753b4c40-6a02-11e6-95b9-a16bd7bf47bf.png)

Mobile:

On mobile and small screen, everything goes to one column. The modal is displayed 100% width, as is the standard in Calypso. 

The preview sits below the expanding cards in the main content. The Header cards are slightly altered so that the description is displayed below the title:

![](https://cloud.githubusercontent.com/assets/5835847/17945440/25baf748-6a01-11e6-8b9c-7d264dd945d1.png)

# Full flow, from original design post:

**Orders screen**

If there’s shippable products in the order, you’ll see a ‘Create label’ button in a Shipping Labels metabox.

![step-0-create-label](https://cloud.githubusercontent.com/assets/5835847/17910794/afcab406-6947-11e6-92bd-cf3c50ac2b50.png)

In an ideal world, you’d see this when you pressed the button:

Everything is filled out and the chosen values are displayed as summaries. The label preview is to the right so you know what you are getting and the Print & Purchase button is just waiting for you to press it

![everything-is-good-all-collapsed](https://cloud.githubusercontent.com/assets/5835847/17910809/c2ca6588-6947-11e6-88e2-6824d7dc8f16.png)

You can of course open any of the expanding cards to change and review any of the items. Let me step through each one of those.

**Origin address**

The origin address would display a dropdown for the available addresses. This is to support multi warehouses. If the store is shipping from a single origin, the merchant would likely never need to go into this area.

![origin-address-all-green](https://cloud.githubusercontent.com/assets/5835847/17910903/34d40e40-6948-11e6-9f4a-f91505f9506b.png)

**Destination Address** 

Many addresses will need to be validated. Instead of throwing an alert, we were discussing in our last meeting that it might make sense to auto select the validated address. I think it would be enough to display the validated address would accurately display in the collapsed summary area.

When you expand the box, it would have the suggested address chosen. You could always change it back to the address entered or edit the address.

![destination-address](https://cloud.githubusercontent.com/assets/5835847/17910914/484083a0-6948-11e6-935c-41d8b7d13aa8.png)

**Packages**

Lets take a quick detour and assume that something is missing with packages when you press the ‘Create shipping labels’. All other sections are good to go. Upon opening the modal, the Packages section would be expanded, with the problem in place of the summary.

You’d review the package chosen, and enter the weight.

![new - weight not entered](https://cloud.githubusercontent.com/assets/5835847/17910984/b05604d8-6948-11e6-9e8b-ca616dc075a0.png)

Once the weight is entered, the warning goes away:

![new - weight now entered](https://cloud.githubusercontent.com/assets/5835847/17911004/cab1a67a-6948-11e6-9f01-8085971118bc.png)

**Rates**

Rates is the last expandable card. Like the previous card, its broken up in to packages. You chose from a list of available rates and whether or not you’d like to display the postage price on the card. We were thinking the default would be not to.

![reviewing-rates](https://cloud.githubusercontent.com/assets/5835847/17911023/e74fa264-6948-11e6-9794-2944ff66ce1c.png)

Still to do: 

- [ ] **Layout**: make it more apparent when scrolling
- [ ] **Packages step**: Display products in box
- [ ] Reference payment method, last 4 digits of card? (Won't be editable, user will do this in settings)
- [x] Include mobile design

Questions:

Do we need to display paper size or can we let the printer dialog handle that?

**Comment by kellychoffman** [comment]
> Do we need to display paper size or can we let the printer dialog handle that?

For now, no. (TODO: Revisit this after Sprint 5)

**Comment by allendav** [comment]
Closing this issue - will tackle little things in new issues
