### ISSUE TITLE
[Labels] Rates step UI (one package only initially) Design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#510]
Design for issue #506 (@jeffstieler) of the same name. 

![](https://cloud.githubusercontent.com/assets/5835847/17911023/e74fa264-6948-11e6-9794-2944ff66ce1c.png)

Header: 

- gridicon `checkmark` or `notice-outline` depending on status
- title: `Rates`
- description: Rate selected followed by a price. Example: `Parcel Post: $9.01`

'Hide postage price on shipping label' radio option should be selected by default.

To do: 

- [x] Add indicator if rates selected doesn't match rate customer selected at checkout (make generic so we can use for all instances. 

Full flow: #501

**Comment by jeffstieler** [comment]
@kellychoffman if there was a second package, would it be displayed inline under the first one?

**Comment by jeffstieler** [comment]
Also, if there are multiple packages, what should display in the "summary" text for the Rates foldable card?

**Comment by kellychoffman** [comment]
> if there are multiple packages, what should display in the "summary" text for the Rates foldable card?

For multiple packages, I think it would make the most sense to just display the total rate and skip the service name. 

`Total rate: $30.53`

<img width="600" alt="screen shot 2016-08-26 at 2 34 55 pm" src="https://cloud.githubusercontent.com/assets/5835847/18019636/48cc776c-6b9a-11e6-8e9a-ee7e259aebcd.png">

For single packages: 

<img width="583" alt="screen shot 2016-08-26 at 2 35 25 pm" src="https://cloud.githubusercontent.com/assets/5835847/18019659/5b5dbc38-6b9a-11e6-8ccb-15936da53b44.png">

**Comment by kellychoffman** [comment]
>  if there was a second package, would it be displayed inline under the first one?

I thought about this a bit more and my original idea of displaying them all inline doesn't make sense. More specifically, I don't think repeating the price display for each package makes sense. That setting should apply to all packages. 

I think we should list out the multiple packages on top, and the price display below. Like:

<img width="583" alt="screen shot 2016-08-26 at 2 38 04 pm" src="https://cloud.githubusercontent.com/assets/5835847/18019743/c6346aca-6b9a-11e6-9053-412d25c09818.png">

This slightly changes the single package display, in that the `Package 1 (of 1)` would go away: 

<img width="584" alt="screen shot 2016-08-26 at 2 38 12 pm" src="https://cloud.githubusercontent.com/assets/5835847/18019755/d3c6f252-6b9a-11e6-9149-6854502dcb48.png">

**Comment by kellychoffman** [comment]
>  Add indicator if rates selected doesn't match rate customer selected at checkout (make generic so we can use for all instances.

I was thinking that this notice made more sense as informational instead of a warning. Do you agree? Also, do you think it makes sense to add this per package:

<img width="584" alt="screen shot 2016-08-26 at 3 06 41 pm" src="https://cloud.githubusercontent.com/assets/5835847/18020491/d1e93f90-6b9e-11e6-975a-e7dd2d74c136.png">

or overall:

<img width="582" alt="screen shot 2016-08-26 at 3 14 11 pm" src="https://cloud.githubusercontent.com/assets/5835847/18020665/d152746a-6b9f-11e6-90bd-fd234e4d87b5.png">

(Copy up for review)

**Comment by jeffstieler** [comment]
Sorry @kellychoffman, I'm just now getting to this.

> I was thinking that this notice made more sense as informational instead of a warning. Do you agree? 

Agreed. I think the "overall" version of this notice makes the most sense, since the customer isn't able to select different services for the packages in the order.

**Comment by allendav** [comment]
This is closeable - we'll tackle the red alert in its own new issue
