### ISSUE TITLE
Clean up onbeforeunload handling for our "apps"

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#516]
Instead of having main.js aware of form state internals, each app (e.g. payment method, instance settings, etc.) should take care of onbeforeunload itself

Ref: https://github.com/Automattic/woocommerce-connect-client/blob/master/client/main.js#L32 and https://github.com/Automattic/woocommerce-connect-client/pull/488#issuecomment-242998530

**Comment by DanReyLop** [comment]
Fixed by #529
