### ISSUE TITLE
Webpack source maps don't always work with Chrome

### ISSUE THREAD

**Issue by robobot3000** [Automattic/woocommerce-connect-client#517]
I started experiencing this webpack issue: https://github.com/webpack/webpack/issues/2145
The breakpoints weren't getting hit when debugging. It's pretty intermittent, because it used to work for me before.

Changing the `devtool` in webpack config from `eval-source-map` to `inline-source-map` fixed it. This should be investigated and potentially committed to our repo if the performance is not affected.

**Comment by DanReyLop** [comment]
Changing what to what? You put the same option twice :D
If you tried and it works, just commit it, performance is not a big issue in development mode (since webpack does incremental builds)
