### ISSUE TITLE
[Labels] Allow the merchant to refund a label: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#521]
Design issue for https://github.com/Automattic/woocommerce-connect-client/issues/433 (@DanReyLop) of the same name.

Refund flow and design

- confirmation modal
- button in metabox
- success message

**Comment by kellychoffman** [comment]
From the refund metabox, click 'Refund label': 

![screen shot 2016-09-05 at 8 31 35 pm](https://cloud.githubusercontent.com/assets/5835847/18260070/cabce684-73a7-11e6-86fe-84aaeea7d00c.png)

A modal appears, which acts as a confirmation. The merchant reviews everything and confirms.

![screen shot 2016-09-05 at 8 31 23 pm](https://cloud.githubusercontent.com/assets/5835847/18260069/caba7174-73a7-11e6-8086-b079a33a7078.png)

Upon confirming, a success message appears on the Orders page: "Shipping label successfully refunded."

Questions: 

Do we want to position this as submitting a refund or submitting a _request_ for a refund? Which is more accurate. What happens if the request does not go through? 

cc: @allendav @DanReyLop

**Comment by nabsul** [comment]
I believe we need it to be for a request, as the refund will not necessarily be instantaneous.

**Comment by kellychoffman** [comment]
Based on today's discussion:

- Change copy to be 'request' for refund. 
- Which means add status section: Submitted, Refund success, Refund failed. 
- On page load, check refund label window and either hide or disable Refund label button.

**Comment by DanReyLop** [comment]
`Ship Date` is essentially ignored by all major providers. Should we put something more valuable in the metabox? We have, for example, the timestamp of when the label was purchased.

**Comment by kellychoffman** [comment]
> We have, for example, the timestamp of when the label was purchased.

Good idea. 

![screen shot 2016-09-07 at 1 26 28 pm](https://cloud.githubusercontent.com/assets/5835847/18325510/c151c350-74fe-11e6-874c-775f3682eb9b.png)

**Comment by kellychoffman** [comment]
> Change copy to be 'request' for refund.
> Which means add status section: Submitted, Refund success, Refund failed.
> On page load, check refund label window and either hide or disable Refund label button.

Updated flow for refund:

Printed label metabox:
![screen shot 2016-09-07 at 9 08 25 pm](https://cloud.githubusercontent.com/assets/5835847/18335783/5911bbec-753f-11e6-890d-92719df8da6f.png)
Click on refund label, modal pops up:
![screen shot 2016-09-07 at 9 08 32 pm](https://cloud.githubusercontent.com/assets/5835847/18335784/59264aee-753f-11e6-8f04-c76f0e9e3e4b.png)
After confirming, the refunded metabox:
![screen shot 2016-09-07 at 9 08 40 pm](https://cloud.githubusercontent.com/assets/5835847/18335785/5942e4a6-753f-11e6-8901-aa6e4ef2a66d.png)

@DanReyLop think that makes more sense?

**Comment by DanReyLop** [comment]
@kellychoffman Totally. I'll have it ready for you before you do the dry-run :)

**Comment by allendav** [comment]
See also #562 for new requirements for the meta box

**Comment by allendav** [comment]
We'll tackle the loose ends in the sidebar issue. Closing this one
