### ISSUE TITLE
Error message in labels modal easy to miss

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#530]
When I first tried out this UI and entered an invalid address, I completely failed to notice the error message at the top. I assumed that something was crashing in the background and nothing was actually happening.

I think the error message needs to be:
- a little longer (like: the address doesn't appear valid, please correct it)
- Either place the message closer to the "use this address" button or attract the user's attention to the top of that box somehow. With my eyes focused below, I completely missed the message.

![image](https://cloud.githubusercontent.com/assets/11143071/18257658/29147822-737c-11e6-80fd-a58dc0a65c38.png)

What do you think?
@DanReyLop @kellychoffman

**Comment by kellychoffman** [comment]
If the address is 'invalid', the field(s) that is causing the error should be highlighted red with the contextual error message so you know the 'why' of the error.

In other words, it should behave like the empty required field error:

![screen shot 2016-09-07 at 3 10 31 pm](https://cloud.githubusercontent.com/assets/5835847/18328733/6553088e-750d-11e6-822a-3720a3453668.png)

**Comment by DanReyLop** [comment]
We have no way of knowing which fields are responsible, USPS only gives us a vague generic error response. We canput custom error messages in the fields, but we need to decide in which fields to put it. Maybe in `address`? `This address was not recognized`?

**Comment by kellychoffman** [comment]
Didn't know that, thanks for the info. 

>  Maybe in address? This address was not recognized?

👍  Yeah I like that idea, lets do it.
