### ISSUE TITLE
Display the blog owner's WordPress.com username in payment method settings

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#536]
Right now, there is no way to know which WordPress.com user's payment methods are being displayed. Clicking on the link (which takes you to /me/billing) could be confusing if the current administrator has a WordPress.com account and is a different person than the blog owner:

![screen shot 2016-09-06 at 1 11 04 pm](https://cloud.githubusercontent.com/assets/1595739/18289328/ce9b2612-7433-11e6-9791-466a62b1e332.png)

**Comment by allendav** [comment]
In fact, maybe we shouldn't even linkify WordPress.com if the current user isn't the blog owner

**Comment by allendav** [comment]
Not sure how easy this is to get out of Jetpack, so assigning it a preliminary estimate of 3

**Comment by jeffstieler** [comment]
> Right now, there is no way to know which WordPress.com user's payment methods are being displayed.

It looks like in our requests, we *only* use the Jetpack "master user" token - so basically we only ever show the payment methods of the "master user".

If we're only looking to expose this screen to the master user, all we need to do is compare user ids.

**Comment by allendav** [comment]
> If we're only looking to expose this screen to the master user, all we need to do is compare user ids.

The screen is only fully relevant to the master user, but I am thinking all other users should at least see a prompt (to have the master user login to make changes) instead of no page at all.
