### ISSUE TITLE
Service type 'boxes' does not reference an array

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#545]
Hey @robobot3000 - I think your promotion of boxes in the schemas object in https://github.com/Automattic/woocommerce-connect-client/pull/532 might be causing this error to be logged

```
[08-Sep-2016 20:26:55 UTC] service_type_not_ref_array Malformed service schemas. Service type 'boxes' does not reference an array. (fetch_service_schemas_from_connect_server)
```

**Comment by robobot3000** [comment]
@allendav - did you update/rebase your client branch? With both the client and the server at the latest `master` I'm not getting this error.

**Comment by allendav** [comment]
Yep, it was an older client. As we chatted in slack, we've tended to avoid "breaking" changes like this to the client, to avoid disrupting alpha testers, but I think we can do this a bit now since alpha is super old and we are gearing up for beta.

Getting a sandbox server up and running will help with this too
