### ISSUE TITLE
Leave/stay message after saving payment method

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#548]
After I select a payment method and click save, I get the leave/stay warning when I try to go to another page
![image](https://cloud.githubusercontent.com/assets/11143071/18371881/d7265ff8-75ec-11e6-8703-af1e2991341a.png)

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-connect-client/pull/641.
