### ISSUE TITLE
Two error messages on order page after successful purchase

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#550]
I'm not sure where they're coming from. Here's a screen shot
![image](https://cloud.githubusercontent.com/assets/11143071/18371938/4b1d3940-75ed-11e6-880d-69196cbdaf93.png)

**Comment by allendav** [comment]
See also #554

**Comment by DanReyLop** [comment]
This should be solved by https://github.com/Automattic/woocommerce-connect-client/pull/564
