### ISSUE TITLE
Design: Refine Purchase Label Meta Box

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#562]
@kellychoffman - I was looking for mocks for the purchase label meta box and could not find them - if they exist please paste them here and then we'll close this issue.

The Shipping Label meta box should include:
- a Create Label button if a label has not yet been purchased for the order
- a Reprint Label button for each label purchased in the order
- a Refund Label button for each label purchased in the order and the label was not purchased more than 30 days ago
- a warning that refunds will take at least 14 days to process (this idea was proposed during Happiness Academy)
- a reverse chronologically sorted action log of create, reprint, and refund actions with date and username of action initiator
- the state of any refund label request (pending, refunded, declined)
- a spot for tracking information for each label that supports it ( see also #482 )

The design will take multiple packages/labels into account and make it easy to ensure you are taking the action on the specific label you want to.

The ideal design will hide the complete action log and just show the most recent actions - with some means of expanding to show the complete log.

**Comment by allendav** [comment]
Please also include price paid for each label

**Comment by allendav** [comment]
Please also consider how this might work with order notes, either as part of order notes or by mimicking/improving the UX of order notes

**Comment by jameskoster** [comment]
Here's my first pass at this. 

Default meta box is basically the same as it is now;

![meta-box](https://cldup.com/7yhFiWGGkX.png)

Here's how it looks with content:

![meta-box-content](https://cldup.com/XTlNn9_wS4.png)

'Label Identifier' is a placeholder. Not sure what text we'd use there?

I decided to separate the log into a separate box as it seems kinda situational. This way it can be hidden entirely or moved somewhere less prominent if desired.

I assume that refunded labels cannot be reprinted? Could be wrong though xD

Definitely keen for feedback on this @kellychoffman

**Comment by kellychoffman** [comment]
> Here's how it looks with content:

Very cool. One concern I have is with the relative size and importance of the print action. Since this is the view for labels that have already been purchased and printed, I think we should make this less prominent. Maybe just as a button labeled 'Reprint'? Or 'Print' if there is there a scenario in which the label never printed, but the 'Create new label' modal has been closed. cc-ing @allendav here for feedback here. Any other scenarios I'm missing? 

> 'Label Identifier' is a placeholder. Not sure what text we'd use there?

Would this link you back to the label? Maybe we could get rid of the label identifier all together and just rely on the Reprint button. 

I like the refund pending and declined styles. Should we add a `?` or something that the user can click on to see why it was declined? Even if its just a list of reasons why. Should the 'refunded' status be green with a date that the refund was processed? @allendav: do we have access to this information? 

> I assume that refunded labels cannot be reprinted? 

Correct!

**Comment by jameskoster** [comment]
Good points, I'll revise.

**Comment by jameskoster** [comment]
Here's a couple of alternative label layouts;

![labels](https://cldup.com/7eL7R45HPb.png)

**Comment by allendav** [comment]
Instead of `Refund` I prefer we are explicit about the action and say `Request Refund`

**Comment by allendav** [comment]
> Should the 'refunded' status be green with a date that the refund was processed? @allendav: do we have access to this information?

@kellychoffman - we do not have that - I have opened issue #645 to obtain that info but it may not be accepted into MVP

**Comment by allendav** [comment]
Let's not show the reprint action for labels more than say 1 week old.  (cc @jeffstieler  - do you concur)

**Comment by allendav** [comment]
Also, let's not show the request refund action for labels more than 30 days old

**Comment by allendav** [comment]
@kellychoffman @jameskoster - instead of the "for Product Name" part, what if we had a "Details" affordance that, when clicked, revealed a list of the package contents (product item names)

That could help the merchant answer the (customer) question - in the case of multiple packages in an order - which package was item X shipped inside?

**Comment by allendav** [comment]
Last thought - should "Create New Label", appear at the top of the list, since, chronologically, it is "newer" than the history (and that may help keep it above the fold too.)

**Comment by kellychoffman** [comment]
@allendav  Should we add a link that allows the merchant to view the label preview of an already printed label?

**Comment by allendav** [comment]
> Here's a couple of alternative label layouts;

I really like the left-hand one - I especially like how it separates Refund and Reprint to avoid accidentally clicking the wrong one

**Comment by allendav** [comment]
> @allendav Should we add a link that allows the merchant to view the label preview of an already printed label?

@kellychoffman - I can't think of a solid use case for that, so I'm thinking not - did you have one in mind?  I think the OS/Browser print preview will probably be sufficient for reprints

**Comment by kellychoffman** [comment]
> I can't think of a solid use case for that, so I'm thinking not - did you have one in mind? I think the OS/Browser print preview will probably be sufficient for reprints

At first I was thinking we could use it to differentiate between a few labels in the list, but I think listing out the items in each package (label) would be better.

**Comment by jameskoster** [comment]
> Let's not show the reprint action for labels more than say 1 week old. (cc @jeffstieler - do you concur)

What's the reason for this? I mean, sure, merchants should be printing labels way before a week has passed, but on the odd occasion one _does_ forget... shouldn't they still be able to print it?

> Last thought - should "Create New Label" appear at the top of the list, since, chronologically, it is "newer" than the history (and that may help keep it above the fold too.)

Yeah, I was going to do this. Good call.

Updated design;

![labels-meta](https://cldup.com/7_HKgsCfFu.png)

**Comment by allendav** [comment]
@jameskoster - that design looks awesome :)

The 1 week old is kinda a leftover post office expectation on how long a label can "sit"

**Comment by jameskoster** [comment]
> The 1 week old is kinda a leftover post office expectation on how long a label can "sit"

Makes sense!

**Comment by allendav** [comment]
Maybe we could add the box name and service to the popup? e.g.

<img width="445" alt="screen shot 2016-11-14 at 7 57 09 am" src="https://cloud.githubusercontent.com/assets/1595739/20271724/8acd5156-aa40-11e6-9139-3a5ff095c256.png">

**Comment by allendav** [comment]
@kellychoffman @jameskoster - looks like this design is good to go then (with the box name and service added to the popup - but not in red letters :P ) ?

**Comment by jameskoster** [comment]
Oh I don't know, those red letters look pretty nice, especially with the fetching stoke / shadow.

(Yeah I reckon it's ready to go).

**Comment by allendav** [comment]
Ty! We'll get started on bringing this to life then :)
