### ISSUE TITLE
Add shared packages to shipping method instance

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#566]
i.e. make any changes called for by design in https://github.com/Automattic/woocommerce-connect-client/issues/502

cc @robobot3000 @kellychoffman 

edit: see also https://github.com/Automattic/woocommerce-connect-client/issues/449#issuecomment-249657112 for shared (custom) packages in the labels ui

**Comment by robobot3000** [comment]
This exists already as a link at the bottom of the shipping zone settings page:
<img width="691" alt="screen shot 2016-10-06 at 16 22 55" src="https://cloud.githubusercontent.com/assets/800604/19158606/469bbe14-8be1-11e6-8d46-7c77b52ce4cc.png">

Agreed with @kellychoffman that this is enough for now. In the future we might want to disable/enable packages per shipping zone, but this doesn't seem like a necessary use case at the moment
