### ISSUE TITLE
Allow the merchant to manually add a new package to the shipment

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-connect-client#569]
As part of #449 , in the `Packages` step, allow the merchant to add a package to the shipment. That means, independently of what the packing algorithm decided, the merchant must be allowed to add a box (from the Package Manager) and put one or several of the order's items in that box.

Note: The UI must allow somehow to add a new type of package. We could simply put a link to the `Package Manager`, but then we must make sure that the packages list in the Labels UI are updated without reloading the page.

**Comment by kellychoffman** [comment]
> Note: The UI must allow somehow to add a new type of package. We could simply put a link to the Package Manager, but then we must make sure that the packages list in the Labels UI are updated without reloading the page.

This brings up a good point about the shipping labels UIs for when there are zero saved packages. What about doing this?

<img width="589" alt="screen shot 2016-10-04 at 12 11 54 pm" src="https://cloud.githubusercontent.com/assets/5835847/19082373/e3fb4e34-8a2b-11e6-8d6d-116091f6482f.png">

**Comment by DanReyLop** [comment]
Looks good. It would also be useful to have that link even if the user has saved packages. Something like having a `<select>` with the last option being `Ad a package...` that takes you to the Packaging Manager.

**Comment by kellychoffman** [comment]
> a <select> with the last option being Add a package...

Great idea. Since it would be strange to have that option be the only option in the select, we should have 'Add a package...' be the last item when there is at least one option present, like in  https://github.com/Automattic/woocommerce-connect-client/issues/585#issuecomment-251386056.
