### ISSUE TITLE
Allow the merchant to remove packages and items from a label purchase

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-connect-client#570]
As part of #449 , in the `Packages` step, allow the merchant to remove packages from the shipment.

What should we do if the merchant removes a package with several items in it? My 2 cents:
- If the package is _not_ empty, move its contents to individual packages.
- Items can be removed individually, and that means they are removed for good (at least until the user refreshes the page). That would allow the merchant to print labels only for parts of an order.

**Comment by kellychoffman** [comment]
>  means they are removed for good

Where would they go?

**Comment by DanReyLop** [comment]
> whats the use case for removing them all together?

This ties in with the "I want to print labels only for some of the items" scenario. So the merchant can print labels for a few of the items, but send other items offline (maybe they are extra-fragile and doesn't trust USPS, or they're above the weight limit and it requires an specialiced carrier).

> Where would they go?

They would disappear from the Labels dialog but they would be still in the order, so if the user refreshes the page they would re-appear. I think this would be the way to go, generally: the changes made in the Labels UI (Packaging, destination address, etc) should **not** overwrite the data that the order already has. But that's just my 2 cents.

**Comment by kellychoffman** [comment]
That makes a ton of sense. I think this is the way to go as long as the UI is clear that the items aren't being deleted, we are just removing it from this particular shipping label order. But that should be fairly easy to do. Thanks!
