### ISSUE TITLE
Allow the merchant to move items between packages: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#583]
Design task for: https://github.com/Automattic/woocommerce-connect-client/issues/568 of the same name

**Comment by kellychoffman** [comment]
Lets move some packages!

Lets say you want to ship an order with four items. You get to the packages step and see there are two packages with two items in each one. You know that you can fit one of the items in package two into package one. 

So since we are thinking mobile first, and we will need a non drag and drop interface to work on touch screens, my solution is as follows: 

You check the box next to the item you wish to remove. The actions button activate and you press `Move`:
![slice 3](https://cloud.githubusercontent.com/assets/5835847/19074200/206b771e-8a0d-11e6-98a5-a9de5645a7ba.png)

A dialog appears and you select which package to move it to:
![slice 4](https://cloud.githubusercontent.com/assets/5835847/19074201/206dc1c2-8a0d-11e6-947e-7a0ef3c70585.png)

The dialog closes and you'll see that the item is in its new place.

**Comment by kellychoffman** [comment]
cc @allendav and @DanReyLop for feedback

**Comment by DanReyLop** [comment]
What do you think will be the most common use case? Move/Delete a single item of a package, or Move/Delete several items of the same package? I would _guess_ that the most common case would be moving/deleting a single item. That means that it would be better to remove the checkboxes and put the Move/Remove buttons on every item line. They could even appear only when the mouse is hovering the item, to reduce clutter (this step is starting to have way too many elements).

**Comment by kellychoffman** [comment]
Iterating on this design, with a draggable interface:

<img width="821" alt="screen shot 2016-10-09 at 10 22 43 pm" src="https://cloud.githubusercontent.com/assets/5835847/19225707/efb7e25e-8e6e-11e6-9d34-64dabb0c81f6.png">

Just not sure it would be apparent that you could drag it up to the other packages 🤔

**Comment by kellychoffman** [comment]
Iterating on moving packages UX, focusing on non drag and drop interface:

<img width="578" alt="screen shot 2016-10-12 at 6 29 09 am" src="https://cloud.githubusercontent.com/assets/5835847/19310128/cdd10b1a-9045-11e6-867f-73b7f649fe03.png">

Contents are listed out and you can either Move or Remove (`x`). Lets focus on moving. Press the Move button and choose which package you'd like to move it to:

<img width="579" alt="screen shot 2016-10-12 at 6 39 38 am" src="https://cloud.githubusercontent.com/assets/5835847/19310312/acb78e6c-9046-11e6-9f69-9e94c73eeaaf.png">

**Comment by DanReyLop** [comment]
Since the `X` already puts the items in the "Save for later" category, should we remove the "Save for later" option from the "Move item" modal?

Also, I would prefer the "Saved for Later" category to be clickable and that takes you to the list of "Saved for later" items. That way, there's a little less noise on the sidebar. But the way you put it looks more consistent, so I don't have a strong opinion either way.

**Comment by kellychoffman** [comment]
> Since the X already puts the items in the "Save for later" category, should we remove the "Save for later" option from the "Move item" modal?

Yeah, that was a bit tricky. I was thinking if you already had something that was in the Saved for later category, you might think you'd have to _move_ it. 

> Also, I would prefer the "Saved for Later" category to be clickable and that takes you to the list of "Saved for later" items. That way, there's a little less noise on the sidebar. But the way you put it looks more consistent, so I don't have a strong opinion either way.

Great idea. It makes much more sense to have them all listed in one page, than to click on them individually. 

<img width="580" alt="screen shot 2016-10-12 at 6 53 37 am" src="https://cloud.githubusercontent.com/assets/5835847/19310723/bd461116-9048-11e6-86d8-0617683707ae.png">
