### ISSUE TITLE
Allow the merchant to manually add a new package to the shipment: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#584]
Design task for https://github.com/Automattic/woocommerce-connect-client/issues/569 of the same name.

**Comment by kellychoffman** [comment]
I commented on the original post instead: https://github.com/Automattic/woocommerce-connect-client/issues/569#issuecomment-251435896 Reposting here:

Manually adding a package when there are NO saved packages:

![](https://cloud.githubusercontent.com/assets/5835847/19075033/199f0302-8a11-11e6-8c88-50dab448d95a.png)

Manually adding a package when there ARE saved packages: 

<img width="536" alt="screen shot 2016-10-07 at 12 58 34 pm" src="https://cloud.githubusercontent.com/assets/5835847/19198570/d439306a-8c8d-11e6-882b-062413639780.png">

(The *last* item in the dropdown is `Add a package...`)

**Comment by kellychoffman** [comment]
cc @allendav and @DanReyLop for feedback

**Comment by DanReyLop** [comment]
We still need a dropdown to add a new package to the order, not only for changing the package a group of items will use. Maybe above the `PACKAGE 1 OF 2` headline? Or bellow everything? I'm referring to the use case of "I'm gonna split those items in 2 boxes, to be able to bubble-wrap them like crazy".

I'm confused. What does the "Add a package..." option do? Opens the Package Manager? If the UI already shows a link to the Package Manager, then it's not needed.

**Comment by kellychoffman** [comment]
> I'm confused. What does the "Add a package..." option do? Opens the Package Manager? If the UI already shows a link to the Package Manager, then it's not needed.

Yep, just a different way of getting to the same place, depending on the context.

**Comment by kellychoffman** [comment]
> We still need a dropdown to add a new package to the order, not only for changing the package a group of items will use. Maybe above the PACKAGE 1 OF 2 headline? Or bellow everything? I'm referring to the use case of "I'm gonna split those items in 2 boxes, to be able to bubble-wrap them like crazy".

I was thinking we could add it below the packages listing/navigation (as introduced in PR #583)

<img width="586" alt="screen shot 2016-10-10 at 12 58 41 pm" src="https://cloud.githubusercontent.com/assets/5835847/19244270/915e88cc-8ee9-11e6-9da5-6761cacc0ffe.png">

**Comment by kellychoffman** [comment]
Iterating on this design a bit:

<img width="578" alt="screen shot 2016-10-12 at 6 29 09 am" src="https://cloud.githubusercontent.com/assets/5835847/19310012/1028beda-9056-11e6-8f8b-959dbb5c3a0d.png">

- Add a package is in left 'nav' 
- packages have counters, indicating how many items are in each

**Comment by DanReyLop** [comment]
This is looking very good :)

As a personal opinion, I prefered the "Bike Box" dropdown instead of the text-only version + button.

I kinda liked the idea of having the last option of the dropdown be a `Take me to the Package Manager` shortcut. That way, we don't need the description with the link below the dropdown. In this screen, the dropdown will **never** be empty (if you are editing the contents of a custom box, then you already have at least 1 type of custom box defined).

**Comment by kellychoffman** [comment]
<img width="582" alt="screen shot 2016-10-12 at 6 58 32 am" src="https://cloud.githubusercontent.com/assets/5835847/19310873/6fd07876-9049-11e6-8af6-0ef3f5a0c80e.png">

Iterated on this a bit more, and I think we can have the best of both worlds. Keeping the dropdown but removing the label and description is still intuitive and we solve the clutter problem while still making it easy to change/add if you need to.
