### ISSUE TITLE
Allow the merchant to remove packages and items from a label purchase: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#585]
Design task for https://github.com/Automattic/woocommerce-connect-client/issues/570 of the same name.

**Comment by kellychoffman** [comment]
**Remove a package:** 

Under each package listing, there is a small, red link that says `Remove package`. Click on that to remove the package:
![slice 3](https://cloud.githubusercontent.com/assets/5835847/19075033/199f0302-8a11-11e6-8c88-50dab448d95a.png)

If there are items in the package, this confirmation dialog appears:

<img width="500" alt="screen shot 2016-10-04 at 9 20 25 am" src="https://cloud.githubusercontent.com/assets/5835847/19075649/d925db54-8a13-11e6-8f49-0afa34d5fbd8.png">

If there are no items in the package, this confirmation dialog appears:

<img width="499" alt="screen shot 2016-10-04 at 9 21 50 am" src="https://cloud.githubusercontent.com/assets/5835847/19075694/0b140f1e-8a14-11e6-9bd2-f7132b6ce60c.png">

**Comment by kellychoffman** [comment]
**Remove an item:**

Lets say you want to remove an item (or multiple items) from a package. You would follow a very similar flow to moving an item as seen in #583.

Select a the item(s) you want to move:

![slice 3](https://cloud.githubusercontent.com/assets/5835847/19078971/000b92de-8a20-11e6-8ac4-54b4d888d213.png)

Press the now active Remove button:

![remove item](https://cloud.githubusercontent.com/assets/5835847/19079027/3166e7d4-8a20-11e6-9910-d452d74df736.png)

Confirm, the dialog closes, and the items is no longer there.

**Comment by kellychoffman** [comment]
cc @allendav and @DanReyLop for feedback

**Comment by DanReyLop** [comment]
What do you think, instead of the confirmation dialog, just remove the items and put a floating "Undo" button somewhere for a few seconds? I've seen that pattern in several sites and I find it much less intrusive than a confirmation dialog.

**Comment by kellychoffman** [comment]
My only thought was that there would be no way to undo it if you happened to miss the temporary undo.
