### ISSUE TITLE
In Edit Order, tell the merchant what box(es) the server picked for the item(s) in an order: design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#586]
Design issue for #312 of the same name.

**Comment by allendav** [comment]
Since this is Edit Order (and not Labels UI specifically) this can be a lower priority for Sprint 6 than the other issues that concern themselves with Labels UI.

**Comment by allendav** [comment]
Parking this issue - since we are going to add this to the labels meta box ala https://github.com/Automattic/woocommerce-connect-client/issues/562 we don't need to invest in this right now (and what with s9n too)

**Comment by robobot3000** [comment]
This was added in #713
