### ISSUE TITLE
Server responses not checked for `WP_Error`

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-connect-client#595]
Errors that occur in the API client when making a request to the WCC server are not handled.

Missing `WP_Error` handling:
- [ ] https://github.com/Automattic/woocommerce-connect-client/blob/master/classes/class-wc-connect-api-client.php#L318
- [ ] https://github.com/Automattic/woocommerce-connect-client/blob/master/classes/class-wc-rest-connect-address-normalization-controller.php#L66

**Comment by allendav** [comment]
Still just a 1 @jeffstieler ? Assigning to you for an updated estimate - not yet in a sprint.

**Comment by jeffstieler** [comment]
This no longer looks like it's an issue.
