### ISSUE TITLE
Connect-a-thon: Unsatisfying response to clicking on Buy & Print button

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#603]
A few people in connect-a-thon remarked that when they clicked on the Buy & Print button, they were expecting something more since nothing (other than disabling the button) happens for **8 seconds**.  We might need an animation or something there?

![8-seconds-of-silence](https://cloud.githubusercontent.com/assets/1595739/19058273/c49aeb18-898a-11e6-9509-d8964334ec69.gif)

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by DanReyLop** [comment]
We already change the component's appearance when the form is submitting. To solve this would be enough to add an spinner inside of the button, for example. I've just checked and there's no problem at all puting an `<svg>` inside a `<button>`.
