### ISSUE TITLE
Connect-a-thon: Exterior dimensions view state persists across modal instances

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#606]
"When creating a new box, once you click "view exterior dimensions", the state never goes back when leaving then clicking back into the box. And the modal overflows when the exterior dimensions are showing."

Props @WPprodigy

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by robobot3000** [comment]
I think I fixed the exterior dimensions thing, so only estimating for the overflowing modal

**Comment by robobot3000** [comment]
Actually, exterior dimensions were fixed in #565 and overflowing modal is covered in #631. Closing this.
