### ISSUE TITLE
Unable to scroll modal content in add package modal

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#631]
The background scrolls instead:

![cant-scroll-modal-content](https://cloud.githubusercontent.com/assets/1595739/19536648/b04274c8-9601-11e6-999a-aafcd7a9e819.gif)

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by DanReyLop** [comment]
This was fixed as part of https://github.com/Automattic/woocommerce-connect-client/pull/719
