### ISSUE TITLE
Allow the merchant to manage flat rate packages from the packaging manager

### ISSUE THREAD

**Issue by robobot3000** [Automattic/woocommerce-connect-client#642]
- the merchant should be able to add and remove flat rate packages per deliverer in the packaging manager
- the shipping instance settings should just show one "Flat rates" service encompassing all enabled flat rate packages
- the label print UI should allow to add flat rate packages to the order, based on what's enabled in the packaging manager

CC @allendav

**Comment by allendav** [comment]
> the shipping instance settings should just show one "Flat rates" service encompassing all enabled flat rate packages

I think this (which i interpret to mean displaying all flat rate services in a single group) isn't necessairily what we want - i think i would just _not_ show not-selected flat rate services in the existing groups (e.g. priority mail) as options instead of having a separate group

**Comment by allendav** [comment]
Might want to turn this into an epic / three separate issues?

**Comment by allendav** [comment]
Let's go with 5 :)
