### ISSUE TITLE
Add a wordpress.org compliant readme.txt and update README.md

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#648]
See https://wordpress.org/plugins/about/readme.txt

Contributors should be set to Automattic, WooThemes, @allendav , @jeffstieler  , @nabsul  , @DanReyLop , @robobot3000  and @kellychoffman?

"Force" opening this to myself for this sprint

README.md should be updated as well for Beta

**Comment by nabsul** [comment]
nabsul

**Comment by robobot3000** [comment]
robobot3000

**Comment by DanReyLop** [comment]
danreylop

**Comment by allendav** [comment]
The readme.txt should also include a link to the detailed data doc.
