### ISSUE TITLE
Design: Errors continue to be displayed "below" the labels modal

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#649]
Errors that occur while using the label modal should appear in the modal itself, not beneath it.

Needs design.

<img width="467" alt="screen shot 2016-10-27 at 11 33 04 am" src="https://cloud.githubusercontent.com/assets/1595739/19780324/792085f0-9c39-11e6-9761-9eccf0180e9d.png">

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by DanReyLop** [comment]
Would this be enough if the errors showed *above* the modal (not inside)? If so, this whole issue can be solved changing a `z-index`.

**Comment by kellychoffman** [comment]
> Would this be enough if the errors showed above the modal (not inside)? If so, this whole issue can be solved changing a z-index.

Yeah, I think thats what we will have to do, especially given the nature of global notices. Did a quick inspector hack:

![screen shot 2016-10-31 at 4 56 20 pm](https://cloud.githubusercontent.com/assets/5835847/19874500/4eaef356-9f8b-11e6-8d82-804460b2d5d7.png)

```
z-index: 999999;
max-width: 800px;
top: 32px;
```

I can open the PR.

**Comment by DanReyLop** [comment]
Wouldn't it be better to change this in `wp-calypso`? They have all these fancy auto-generated `z-index` values: https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/functions/_z-index.scss

We would just need to make the `global-notices` be bigger than the `modal` classes (something that makes sense for WordPress.com too) and update our `wp-calypso` dependency (something we already do on a regular basis).

**Comment by kellychoffman** [comment]
Even better :)

**Comment by allendav** [comment]
Let's go with this :)

**Comment by allendav** [comment]
@kellychoffman @DanReyLop - on further investigation, the global notice z-index was reduced to fall behind the notices (notifications drop down) ( ref https://github.com/Automattic/wp-calypso/commit/508eb0ab85a40404cc6c126f508fd7b55ca524eb )

With global notices at 179 and notices-list at 180 and dialog at 100200 I think we need another solution

**Comment by DanReyLop** [comment]
Then I'm OK manually putting a high `z-index` on our side. I try to avoid fiddling with `z-indices` but this time it's needed :)
