### ISSUE TITLE
Generate a "unique" id when connect is activated for the first time and add it to every request

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#651]
To facilitate anonymous usage data collection, maybe using the RFC4122 technique atom does

<img width="740" alt="atom-2" src="https://cloud.githubusercontent.com/assets/1595739/19787754/4efb4c68-9c59-11e6-9b0f-4ef6072296ec.png">
<img width="589" alt="atom-1" src="https://cloud.githubusercontent.com/assets/1595739/19787755/4efbfb36-9c59-11e6-9264-13d44ded79d4.png">

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by nabsul** [comment]
It should be sufficient to implement this as follows: create a get_uuid function that gets the uuid from the wordpress options table. If the value doesn't exist, it will be created.

**Comment by nabsul** [comment]
Additionally, we should add this uuid field to the settings parameters that are sent with requests to the server.

**Comment by jeffstieler** [comment]
Let's be careful not to use the UUID in our metrics, since it's easy to change via query/filters. :)

**Comment by nabsul** [comment]
Not sure I understand this commend. Will add to our hangout agenda.

**Comment by allendav** [comment]
> Let's be careful not to use the UUID in our metrics, since it's easy to change via query/filters. :)

We will be using it in usage data collection, to uniquely and anonymously identify requests from a store (after stripping site and site owner address and identifying information)

**Comment by jeffstieler** [comment]
> We will be using it in usage data collection, to uniquely and anonymously identify requests from a store (after stripping site and site owner address and identifying information)

That sounds fine.

I should have been more specific - let's not use the UUID to calculate things like "number of sites". :)
