### ISSUE TITLE
Insufficient postage quoted for large flat rate box label

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#706]
I have a USPS Priority Mail Large Flat Rate Box enabled in my packaging manager.

I have both Priority Mail and Priority Mail Large Flat Rate Box enabled in my USPS shipping method. I also have selected "Show all available rates and let customers choose.", "I'll print shipping labels through WooCommerce - charge the discounted price when available." and "When cheaper, pack multiple items in a single package."

I added a single 3.2 pound 11" x 11" x 4" item to my cart.

I was quoted both priority mail ($17.09) and priority mail flat rate ($16.35) shipping during checkout.

I selected priority mail flat rate ($16.35) during checkout.

I checked the USPS business postage calculator for commercial base pricing ( https://dbcalc.usps.com/CalculatorSetPage.aspx#Commercial_Base_Flat_Rate ) and the flat rate amount ($16.35) is correct.

I went to Edit Order to print a label for that order.  I am quoted a too-low, incorrect price for the flat rate box.  I am quoted $14.58. No other rates are available in the drop down.  I stop before committing a felony :P 

![screen shot 2016-11-15 at 11 51 37 am](https://cloud.githubusercontent.com/assets/1595739/20321421/442fc162-ab2a-11e6-9289-90537abd248d.png)

![screen shot 2016-11-15 at 11 54 48 am](https://cloud.githubusercontent.com/assets/1595739/20321446/58e19bd0-ab2a-11e6-8ed3-9aa6ee837517.png)

**Comment by robobot3000** [comment]
@allendav I'm getting a correct price ($16.35) with the same settings. I might need to know what the addresses that you used were.

Could you also change the "I'll print shipping labels through WooCommerce - charge the discounted price when available." option and see if it changes anything for you? It didn't change anything for me, but it sounds like the most obvious thing

**Comment by allendav** [comment]
Closing this issue - its a bug on the server - see https://github.com/Automattic/woocommerce-connect-server/issues/639
