### ISSUE TITLE
Add (custom) package dialog layout is very borked

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#711]
![screen shot 2016-11-15 at 4 40 01 pm](https://cloud.githubusercontent.com/assets/1595739/20330242/3d63f56a-ab52-11e6-945c-954f5d02fe99.png)

cc @robobot3000 @kellychoffman

**Comment by kellychoffman** [comment]
We need to have separate classes for each modal. Each time we add one and style it, another one breaks.

**Comment by allendav** [comment]
It is this change in particular doing it

https://github.com/Automattic/woocommerce-connect-client/commit/c49014175de6c1867a20921770a5f5471d39e72e#diff-71e5f6f03e3a279beddfc328664288eaL169

**Comment by kellychoffman** [comment]
Yeah it also depends on the height of the browser window.
