### ISSUE TITLE
No preview is being displayed when I buy a label

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#722]
Everything else works fine.

![image](https://cloud.githubusercontent.com/assets/11143071/20537113/a8bf61de-b0a0-11e6-840e-21b4fef656a3.png)

**Comment by allendav** [comment]
Workaround until this is fixed: If you toggle the rate to something else, the preview appears

**Comment by allendav** [comment]
Needs estimate first please
