### ISSUE TITLE
"0" and "0.0" dimensions are treated differently for shipping rate requests

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#724]
I've noticed if you set the length of a product to "0" and add that item to a cart and try to get rates, you don't get any rates returned. However, if you set the length of the product to "0.0", the rate request goes out to the server and causes an error on the server side (also resulting in no results).

![image](https://cloud.githubusercontent.com/assets/11143071/20545035/b1f91710-b0c1-11e6-9124-80bb102bd089.png)

**Comment by allendav** [comment]
Note: It is important when editing a product length to change it from "0.0" to something non zero (e.g. 99) before attempting to change it to "0"

**Comment by nabsul** [comment]
I'll take this fix over. I've found the place where this needs to be fixed.

**Comment by nabsul** [comment]
The issue here is that a value of zero somehow gets transformed to an empty value. This is what is getting sent to the server:

```
    "contents": [
        {
            "height": "1",
            "product_id": 37,
            "length": "",
            "quantity": 1,
            "weight": "1",
            "width": "1"
        }
    ],
```

The code doing this is part of WooCommerce Core. Once I have it fixed in our plugin, I'll look into submitting a request there to fix it.
