### ISSUE TITLE
Internal links: remove target="_blank"

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#725]
The link to the Packaging Manager, for example opens a new tab. There could be more. All internal links should open within the same tab.

**Comment by allendav** [comment]
Let's keep terms of service and data privacy opening in new tabs though, right?

**Comment by kellychoffman** [comment]
Yes - those are external links. 

Also, I lied. This link is the only one. Quickly fixing this now...
