### ISSUE TITLE
PHP Notice on Account Settings page

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-connect-client#745]
I see the following using the `master` branch @ 198902bf7ba3c41fe63f91296857d1b832baa144 on the `/wp-admin/admin.php?page=wc-settings&tab=connect` screen:

`Notice: Object of class WP_User could not be converted to int in woocommerce-connect-client/classes/class-wc-connect-settings-pages.php on line 141`

**Comment by allendav** [comment]
Probably collateral from #741 - I'll take a look
