### ISSUE TITLE
"Buy & Print" Button available just before printing a label

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-connect-client#771]
When I click on "buy & print" to purchase a label, it shows a spinner while the processing is happening. However, when the process is complete, the button looks like it's available again for clicking. This last for a second or so until the print dialog pops up. 

Perhaps would could at least make sure the button is shaded in a way that makes it clear it's disabled?

**Comment by nabsul** [comment]
I can confirm that in that split second, I can click that button and it will attempt to purchase labels again.

**Comment by DanReyLop** [comment]
Probably removing these lines should be enough: https://github.com/Automattic/woocommerce-connect-client/blob/master/client/shipping-label/state/reducer.js#L459-L462

That split second is the time between the client receives the purchased labels data and the PDF is downloaded. Keeping the form in the "isSubmitting" state should do the trick.
