### ISSUE TITLE
[Shipping instance] Explain (with a tooltip) why price adjustment is needed

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-connect-client#822]
In the shipping instance configuration, in the "Services" section, explain in a tooltip what are the "price adjustments".

**Comment by kellychoffman** [comment]
Copy:

`Increase the rates calculated by the carrier to account for packaging and handling costs. You can also add a negative amount to save your customers money.`

It might be really long, but at least its ℹ️ informative.
